# Generated by Django 4.2.30 on 2026-09-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_birth_date_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
