# Generated by Django 4.2.30 on 2026-08-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publishing_house',
            field=models.TextField(default='Publishing House'),
        ),
    ]
