# Generated by Django 4.2.30 on 2026-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_author_alter_userprofile_user_and_more'),
    ]

    operations = [
        # Шаг 1: Полностью удаляем старое поле
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        # Шаг 2: Удаляем кастомную таблицу-посредник
        migrations.DeleteModel(
            name='ArticleTag',
        ),
        # Шаг 3: Создаем поле заново с автоматической таблицей
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag'),
        ),
    ]
